# Generated by Django 3.0.3 on 2020-10-15 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='bio of this shop will be show here.', max_length=600)),
                ('location', models.CharField(default='Location', max_length=300)),
                ('dist', models.CharField(default='Location', max_length=300)),
                ('phone_no', models.IntegerField(default='phone number', null=True)),
                ('img', models.ImageField(upload_to='pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
