# Generated by Django 3.0.3 on 2020-10-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20201024_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
