# Generated by Django 3.0.3 on 2020-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20201026_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(default=1231231231, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
